name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  id-token: write     # 关键行！缺了它 OIDC 不会给 token
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # 关键行！缺了它 OIDC 不会给 token
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install -U build twine
      - run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.3
